apiVersion: v1
kind: Secret
metadata:
    name: speakarr-readarr-config-volsync-minio
    namespace: media
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FSge5Jx3hxh5+xZvfz1K46ahOPM=,iv:ISWzhzouZnHqBZUOercRp473P3p22AGWqz2oHzeKvR4=,tag:J5JfZomallPW43j9J7J4SQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bLv/JVRGlqO8GrzXDObcMokcK5lL6/e1bJFkv3FBOyEhgGuzmpAKjA==,iv:dwiSa/BIdj78//IoV5IcLNQEXSxRZS97VHOIaA6LOyU=,tag:gFGmK+mA5shIy5UbIsr6Xw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:M3lVh3Q/5Fnx0MJ9JjSt991Vx85Qt7yzPtKBrMb3cZNbjJLCAtIAzw==,iv:mXmvi9dKVmq3Pbn/4aq6t5GXSU/EUM8k6Y68Sh1wKA4=,tag:jIth7OPVhAKSmq8Nb5rXig==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:84zZzt6G5XG9ty963gfAAFCMFR7faxAQP9X3trmGvrQoWVsBELCNlW+lfjXLfS/vdxqYAX557MlK33ELQbUKTvQ39pZjNFEGM0MM/sJjtZz5sTgzbfVU,iv:LONzZthlO6UauXYT1kByRSUUBnP9+NjqA+gK0YJIK5Q=,tag:+0t3c9hdgJ7HdyfGTYJeYg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcnBzZDNYeUdhQUxtOGJn
            TFM5dzFPMEtWZkdBQnExc1cxZWZMdS85THcwCk1QWldlSVZJMjZOQktJSXNVYzBw
            cGNEQ2h3M3hza3FwZlArRkgxTTFXa2sKLS0tIHNtcTdsWGg3OUNnY2dGd2RBNGdm
            REVuNVhYcEJqV2Q0ZnhORnJ3QSswVjQKPl2QvyVk8bY1fqd8ysJqumU33GV8+vh4
            l1Zn4Ft97ySIPMSKL2IBKQ7MwVe3IsdYXK/Df6jdXDqPRCcSKjTWag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:40:29Z"
    mac: ENC[AES256_GCM,data:MVRJeqJCJchroyyn6saS4/SPG6kq68DcdUfgJmhPIkLaflh8c31Bnwg5pCvXsmGypXTPNMDEy6GdXL3GDcmQJ7gandSNy57trPeeo6367CiezdNHhZOnzeRfEqM6X3enKaxrrIWPRlzTQ+YpHMVgLpYpGdBgvkK1B6LUrM4z9lo=,iv:8kLpis0qASE1QIsJNBi0dN4mB2e26BEYBm73gKfzxFY=,tag:9uupxayb8QUOZEI7NEUWkQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
