apiVersion: v1
kind: Secret
metadata:
    name: speakarr-readarr-config-volsync-minio
    namespace: media
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EW8Mz0sn/bHN+qv1aRpXBA99WFU=,iv:OvtVE0G2Bub7cBG80xV/qatkqgodjvVqUktln6a13CE=,tag:44p5e+woN8HBIOInJCwLYA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6V34AZn+WQGaBhPc3jsvB8axFXVDX66I+EEYB5tP+mSU/8De+/A+pA==,iv:rHC45hpWDvJZ/EhtaPHoFqa1TRMcva5HZUZ8YTB1HQE=,tag:wZ7F6fp/Ge2ecQM1S6jb4w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:351ba+wBDQMnmyjQ8KPXcLGA5AmKEOtKGb0I16QbGjFqiZLl8KhPUQ==,iv:dMJX3CI22XUYV+IulLopymgGSNb5oHf6mUcId8m3TUk=,tag:pl7y0s4VozhXgHy7QcQl/A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:65/G/68/w8/ezu459CSYffV+cDgqrUk4w3dnrWAYKT20ubfhnQG3X+5VZIMqJi52Y0jM9tNoqPLPFI93JhwJFfsRBSYOINBKzyIgXAbSc4bvoBNd9mys,iv:7s2HN8ftx25u27TDFomZUKv0zqsQDtN4UpT9+7CT69M=,tag:pXp9KKai+e+X9LHAGiC80g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d3NsMGVHYU8reW1JaWVv
            L2VHOHJMa0JZL3dUWkxkaHI5dGpwWkFDUTBJCkdxYXNmYjdQWFBMQklOVUk1czBD
            WkF6WStUdFVHNXpLc0RaUkZ2U01EZlUKLS0tIE93bDhWMWtCQVREZGNzU09hRlJW
            Y1RQZGw2eFpXLzgwMmhqeU1IdlA0a28KXGUtqvZYP02hg7PdbWhTevpNRFAtSV47
            hAokmpMPot+1CU7vO28PZDAnD2wNeZKfg8BuoBHKXw0A9dJFdZ/I/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T07:19:50Z"
    mac: ENC[AES256_GCM,data:Uohw2QNN1zHul/Z4riuOyniKtnBi2I4eLUG0VQzZrTy3iKt5ly7fpTmyAyyVvDDrCNUYy7R8PR1BT2u11uSlCRxk6tK0lIvSV6cyLEYLKQttt3aKh+iKW7SzFIgv+GOb06eDjDJgIJPiIX87QukdY3xDiJRdgkLudlmSINhRvtI=,iv:8uhJtrwFOEarawMbvzOv+yjmN6eqH3EP050kwVQVukk=,tag:rIx6+5Ts+47Uw4cvMpyzbA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
