apiVersion: v1
kind: Secret
metadata:
    name: speakarr-readarr-config-volsync-minio
    namespace: media
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4byUytGI9qVmEonFNgLGzqOF3lY=,iv:K7EmbX2PqqAUHp4EXbx3DQWgiToIu/Ct6RfbSE2Qkgg=,tag:IIH9DsgQstbJZZYDpp4AWg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LPEM0FZjLZdyNZYjKNP8Eii//PF1NPTdG1z1U6FZLS4T7UaSQlXWDw==,iv:j0d/z6kXg2VE6ldLxKwkrzppEaGJlbTbffSefOIH4s8=,tag:aw+ML7EsUl+eXWaT+c7zPw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:MJ3e6YLzwff5tOjvWMWNnl69g6UiMuo9D/LIY0AMNAmprdOAjAMgtw==,iv:fNH+Dd0KxWs9kK90QBxfRBB0u++PIL/ckxc6I8LwaAQ=,tag:xDimUK8yWkGRxWQtwq9myg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:07S+nUAKMNVHr7jpiYQz26vKrh+ALlh1cQxu4ZNJE1QoMAFtqi1PeUgjJ2ht/I1PtdWQJdGPaG6Vg5kgQbBUKz2CjXYp3gVbi4pWysA/kntUcK9aIOL8,iv:ad3x4rxM9gj/ZJsXvJ/wpWVvhyALrK2sxfiPYhuYNY0=,tag:ae0Bu+tZdgbMbmhJT9vODg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS29JV214L0pXNG9wRmFt
            YThSVmwzNTE1eGpwTnQ4S00zL1AzOXpBbFdVCnZtRkgxT3BUV2lsSUs5RkZEdTZD
            U09XY2JiNHZFbXRWc09Xd1FkdFBPYUkKLS0tIEJwdGVBWUI2a010S2Nra2dkSzhl
            QVlJL0hscjRGaDNvTTVFZHNDNmVVZFkK5juQ3WncyCHQSdMjbc41qJ3F58S83IOv
            o5KN4icuqLaJO2K/+JQFUw/q2Qd1c0dvti3URGw+EsBirfWxrcb/nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T01:35:46Z"
    mac: ENC[AES256_GCM,data:0dzBVmaNNyHoJLjpyELC8fweFo0pu6xoDaDri8Y2hUgE9b/7WsXP3hYpwWf+naGoXS0I5F4mh3yKtnZGmPXIjW2hXQqhLnDN3YRzpp6u61D81nJ3djxIK4+xE2V5Qv91euUq24k1eenXNxUvt3WR3gTYpbUPAeo1BGA7bnna9pA=,iv:djoadYG1F8TTv/DcVjxPjkV8xmzr/VodmyVwcnYurdw=,tag:6lx2zVpriFBY1WClxU/srg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
