apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wfONapU68e4hWLt3UnWSsS/OIvgRAjb7sHOzDr2osaRYWxMhZrC35pzq0FD57590qOQm3BhUCT9nSLacVVKGjKBwacp//xK1kBhnx9tjUqdUbEsIIr6oZXLfBUJacgBssKnRFq8+DxOlddd46Odc/U99Pp5hN7pT9yNh2EQIkySlPNIjAhbf76ZdEizMMbNJr3RQSAuD58YUZ4pNjTf99sE/HxfodN9TUr9y+eXMzgJ6+/2o60vx5R9wjDXZbcn0hRaI8cKkk09PqA2YjY4/yJNJQ7vC5PXXj3VPM0DX6KVibzXLJ8d9NwDB1Yd8WTjb790cYoaIZaMHSKYfdRVU1kektN8j6I5VyKFN4ChEyrgr/P7W4q5eX5je5cY6eTO8,iv:FxeDxRNq6g+BsAsSrHBEpxutT8VwRc6pDJC40m9ho8k=,tag:W5cPZ8zZFlBEQ3BpgFjIWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:/kJdUFLiWQ1d/UtHFMyzuu4cj4TVFigmsTFjDLQkMlF2QqmjXWJKNxQX4hb7yalnWBAACD7ddHKz0laSD1qHAzeXyfMt1h9OuHrFW6OEZ+Cpv/lH9GR4ZMOFg7yqdLWGx3vXZ3Tl+h1+yVOHXtbqp18JNUs9Ly4llAlcFfgacT6A5Egfz0zosG+D1E9V6fZ2nQHHWub32OWdqB4E4sPWg2PYehjLfz69TSI4ySVg+M07benrfjR9r/5tiydMXBwVl4jnk+4RqnLn1xy0sQ==,iv:0sdBKWBv9S3x98Dw8jY3PT3Cnk1evngVT/P7thscqNI=,tag:sz3rvu7PT53dnWZIy3dCXQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FvMsoALJPvdZYXHKLkvWoCkopMJPU3ofiNOWXzrAdvPQqeF0ObS+r5tGuEhUXPXVXRi022qmB0gLTCf81nDLAJw3XWFCzGKuN4I5+XoA3zHhP8zGJssP1ubQWf29C/1iUoptTgTbN0Q2v+5u+WbZvHIlC79BHHoCae2pSXWQkwOH/Wmm1KRdgAQjA26QXyuVPPaAn/ANJuo+vljlIhISnqXRNRTmbm6ZRbc/,iv:VjtZ1ujNNkwuUbYGAsr+Yr/cm+KsdFQPunMxdq1r/nI=,tag:ASFgWQncHiatzstm3wR+8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYUY4aDdlQ2w1Q01lWW5P
            aUlOdUtSMHFITmZUT2I4WWNJZVhNd1JDQ1ZvClZZK3JhbWNOTlY4N0ROR2tBaHRJ
            bXZCZUsyRitGSXkzclRySHc0Qk5Jb0kKLS0tIHFaVzN6RDFOczNqSEd4dDlZWElI
            YnFidFFNRnVjZlN1VE9vSksxRWVESzAKEIK23/F/dZlO+OFtouQ6MvNQ0N3QyDWO
            uX/NMAcMXPKC9VNFxOs51j2FHHVL4sggXyLk1bqQqnCaD/ydjHxIow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:40:29Z"
    mac: ENC[AES256_GCM,data:uuay9DiBH5vs61BW6/A31E9WGlUbnT6Xh4ZLDl3UUg9gv66zXh65azW5FPbxCq5K36eTeA6JJZ0DQYhZtoILtzteRfmGo/HpFvt7orHVKw1vogxfZpL0UxWzBb+3N3E9DaKLqPz+HKPBuX9bFKZy9lDzpugmOJmD3VQnjb4f+qM=,iv:W9qUpmdMN5860XbsJDkIenvIn5cB2o9NEJW2lki4WOs=,tag:7IR9/+1Gg6iDTFvhQ45qLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
