apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5kcJSFSP+AcVxvtnNYgc0ux5xcQb/ACJLv9OriUJR5bmSIpKO5ZOmT/dyOBbIF0bIiNsViYDLehmHr54/k9hDufbb6y7okR1lHA3HVdHXJUxRKziwgNOXHf3Q9P/lXY1UcCYpp6jVcW0FA0/Lwp9646NqUhk67HGnx9XRUtt8fFBLWJQ4Wky3lZAdAn1fV5pxTCFNED2TtTsgir9LfnVgktxCup6PmvmdEsvz/i+rK04LJpC6/PXFVNYlxBlc5Ie0MsVzWtxyfc6tbIzflQYUFkjWcp3v6AhzKgOJ1YUQ794Ml6TmFi4d0cTCReYJZQ3JcNH9UnHhilB+0/BfI7490Zq9/1xN9hTpuddGI/PCW75L8TOS2EfArnXLUEQxJmG,iv:Di3tJi+lj6P5RRX/Q/ieM54/Eu3a0OJe3tdQEmIsQX8=,tag:A0ChqVUHqhM3C1wpKx5iWQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:rc9v/dsFDdGj8m4KqF1FlPelWAo7PDBcAMRASIKuNTkgg019jV7B6X+Uh93f3KeZvyb++a3t6NZ0TOpwM+LcCZsnNmh7Ei/QOaSt3+m2q/tCgfDsEbWLOZH8Bhzl6kRz6wp6XbyIUX3tLyoIQFEY8flscgulaJzC3L0YY0bgP9vg3moChCXsGSxcjyXJK7oXkAoE4qCHPO3OO+TpiMCP/I931uXwqk53g1xv97wPx6bnwHYwk6OvbWjBYLCH43d2TOkQjYBSh99Kq7qB7g==,iv:nvp41g8DWVjpYjOKFo4OFI+q15vzoHJ75aEkAAVUWvc=,tag:qM5IiEYPDmqtxO1u+vQkeg==,type:str]
    known_hosts: ENC[AES256_GCM,data:65Isd3x0ldbbUhdjDjqRFfQpJIUww1BORTylCVku0fcjCRY5F8Bex+uNqXP+AJFzZyFmDrQif8ronk0OIB5UM+o6VHZUbUN/BljWB4faFh3NN4NZGBOVP1TNOeGXbXSgJFSM6Fs4CzaNiGhqfphVrJPzVfxngF1uoHQ/sjQoUhPchMbCiN2lmWe2O5oKqIQhlWYdESS9K6Z0CYALFVx3KQUhN2pSzMjT9Hdp,iv:k03GcCgWj+sOBaJpunV3rNbjF3tWvZFjevgj4Rn14tk=,tag:qHdYTbf3r0lCMdvw8qt3Hw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTnJxOE9zWFZvVlM1U09O
            ZGZHV09nR3dIN3ZOZTZ3eitTYTJNQks2M3c4CmxyOGpaL1ZaUlFKS01IOTFHYTF2
            K0x0WWZnUmVvaUtFU0M3NDlBTGt0cG8KLS0tIC9LeU9saWpwQXBZRVJSOHczcnhE
            S081R0pyRTZkOVZTeWpvcFVRS2F3cFUK4lcOcguLKW1C0oNZdpw3VSKbuVtLKQ2K
            MXiR0SMBJN+tVNE6Zx4WBzE2DlXXEKUSMTk/dq086PIv2PJQJ8UxSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T07:19:50Z"
    mac: ENC[AES256_GCM,data:XVeOhYFwBsVvCs3iZPYttZDS0sLdch2LF6nXLLiH0+q/2mPeqfCH8spBDX5+z+7N8wP7CAGYa5MNbs4+dycV2qCiXXaluAhDd3XkDTOSCvPaYpYpLe9GEXwDXKVhZa4As0d6APR/60dIEham9IESN+uendpRAhrrWi/FhyEE/Dc=,iv:b4q19+z47uqeYcY3P26GaGqsrnHBUFrvMaMj1tb9GZE=,tag:SwZnjB7tcTNCZe9MG7YrGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
