apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:w3GZKIQ2yDKDSUOfj0hMnpc+HiJpkrUr4dnFCHzledcJPAuzfECUUAhHkckJKgVgfruu9+oMd2OA11LXeukcM/s6gMSzruY/Aq6g1ZZmiWYfTli+CA7dPMQsCGD7LvwfAF23GOUXr5NUA510Lny0m6TWv6MZjh7nXpy91vX6jwe5mhkJM6RNGUAjtusxZCVI6YPgYSXvDbv4aIiBic7DeNlJZhtkOc0y2CcWBHcxTNVk/6i4jbXXjeOXZzwcILE6q0kEhC3xibAc/oUlhUmx7FQa/xt9E3wj2GW36b3F2oqEXYzQWHJ51PpGlLChxkbmiIcvrMO7nmAt4A1wZ3yj8X/vBMEPIFeq/erccqxuOjyEdS6PX0MOGlNTJ8YtO/u/,iv:QDiDSsmZgJziU3zVkqhNMQwr1jIgWY2bhTO0D+9pAFA=,tag:U3aHbNsva/bTU39pviYvJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:X5MNZ2B9XLXnhcn+rZiHMYeKbOW9Blu1iIY/kHhc4ke2KsX4BapJLi3jjWvU3ppUjMsmLCyyrZjiW5fkRVl4sK/7VpT4xc/u0gI9JogBra4iZceGbpEiVdtvvMMw6lsCnzilgKDOi5CZguh25/J6Tl9plX6eucwSIBiBW3vf213HDjnvCyh44CuG9hh8aE0+VRLVsDFZm8Dfnzm20HhC48C0R18zxPODlvzfSuscFyPuHcsnC6MPqntftjvd9wnmpeW0CyWrENdZX406Tg==,iv:+oR+ojFCVPigOVvR6aOhsYXFBzon0P9nMX8Z4m3zZUc=,tag:Bab2lojQjD6nWhE1Q0odSw==,type:str]
    known_hosts: ENC[AES256_GCM,data:x6aYf/o2faVW8K6SjDUE2JOKipRAc93zyrQQUPkYc8LLDnlpk+z/EmKEZUVW3rZu4qZ8yaRRrgcjaEhASRVoyD7uf/wnub+wk+YRl9h/YHf6k6KYt3SEZ+EfsmI8/5H4hq2Ms4OqdgHLeStVUeecbf/JC+7+yHXNP2xqzIe1lz5szrBGJe5xp5ZGBqvYl4gZyr520WD22Nq+LMqhIftI9H+lXvFjLQAoz2lr,iv:hMW3EEATg6CEvXrlax9n3HOaId+EfCrDORmVSlUV428=,tag:6icn8myoerQHvSZAnHD1fw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeXlZeENSWFFpYVlYcC9Z
            RXI2Q2poOHVIbVpXUGxxdVR1bEE5RG1nc3k4CjZtSkt6ZnpwZExZSVBwNFBjQmor
            Z0Z0MHArU0JxZXp5OTRRdWc3RCtqUncKLS0tIHJPK1ZzTUpMT2t6d2tvUmtGdng2
            bG9DM280UHBUUGhUQjVNM01yWVE4N0kK1GMpbwAv7C77x2F0SGyEFAp4/Qtalqvt
            J69aziswLjVkKxc2+EHPMh32kmdGRaC4NFd6hw/oz3Fn5HTHWaNihw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T01:35:46Z"
    mac: ENC[AES256_GCM,data:XH53shs5KzLg/3e88U+evDnlnNm144mui2PGMbNYWoE8xsf4TyjVWPuuFVk74KOJS7aklzAX7CgEAgFcP1V2XkmrC2UJo1Mo76pInM84P5Vya7P1aL0ETZPJXG1hsX3btYDJ4RgqIpOyL//nj1x44w1wZj1hRMzBWbs91CUGEw4=,iv:dGdInvC3+0//ZbhFnm6kYHT9wF22yHV4YJhVOlLRghc=,tag:g1DlDUcNApnSBpT0IC+QUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
