apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: rsshub-secrets
  namespace: rsshub
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: rsshub
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: "${bitwarden_secrets_org_id}"
  secretName: rsshub-secrets
  onlyMappedSecrets: true
  map:
    - bwSecretId: "62c0e26f-41c2-4d6b-889c-b3c90067871d"
      secretKeyName: "ACCESS_KEY"
    - bwSecretId: "212004ee-d883-4692-a8ec-b3c90067c427"
      secretKeyName: "TWITTER_USERNAME"
    - bwSecretId: "b00261ef-60f0-4a82-bc7e-b3c90067dee0"
      secretKeyName: "TWITTER_PASSWORD"
    - bwSecretId: "4f86ec14-5458-47d6-947e-b3c90067adce"
      secretKeyName: "PATREON_COOKIE"
  authToken:
    secretName: bw-auth-token
    secretKey: token
